#pragma once

#define BACKGROUND_ZORDER 0
#define OBJECT_ZORDER 1
#define GROUND_ZORDER 2
#define BOX_HOLD_ZORDER 3
#define CHARACTER_ZORDER 4
#define PARTICLE_ZORDER 5
#define UI_ZORDER 6
#define MENU_ZORDER 7

#define MAIN_LAYER 970112

#define BG_PARTICLE_NODE 100
#define OBJ_PARTICLE_NODE 101
#define CHAR_PARTICLE_NODE 102
#define SCR_PARTICLE_NODE 103
#define CHAR_NODE 104